name: Continuous Integration
on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
  workflow_dispatch:

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
      - name: Install Packages
        run: make install
      - name: Format
        run: make format
      - name: Train
        run: make train
      - name: Debug CML_TOKEN presence
        run: |
          if [ -z "${{ secrets.CML_TOKEN }}" ]; then
            echo "CML_TOKEN is EMPTY"
          else
            echo "CML_TOKEN is SET"
          fi
      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.CML_TOKEN }}
        run: |
          make eval
      - name: Update Branch
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL


